FROM nginx:alpine

WORKDIR /app

COPY ./build /app

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d
COPY ./cert.pem /etc
COPY ./key.pem /etc

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]