version: "3.9"

services:
  web-client:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    container_name: web-client
