FROM node:16 AS build

WORKDIR /origin

COPY ./pacakage.json /origin
COPY ./package-lock.json /origin

RUN npm ci

COPY . /origin

RUN npm run build


FROM nginx:alpine

WORKDIR /app

COPY --from=build /origin/build /app

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]