version: '3.7'

services:
  web-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./.env.development:/app/.env.development
    container_name: web-client
