version: '3.7'

services:
  web-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    image: web-client
    volumes:
      - ./src:/app/src
    container_name: web-client
