version: '3.7'

services:
  web-client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - $key:/etc/key.pem
      - $cert:/etc/cert.pem
    container_name: web-client
    image: web-client
